version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install pdm==2.6
    post_install:
      - pdm sync -G docs
  commands:
    - pdm run docs
    - mv docs/build _readthedocs/html

