version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  commands:
    - pip install pdm==2.7.4
    - pdm sync -G dev -G docs
    - pdm run docs
    - mkdir -p _readthedocs
    - mv docs/build _readthedocs/html
