version: '3.7'

services:
  base: &base
    image: hiku-base
    working_dir: /work
    user: ${CURRENT_UID}
    volumes:
      - ./:/work
    init: true
    environment:
      PYTHONPATH: .
      PYTHONBUFFERED: 1

  docs:
    <<: *base
    image: hiku-docs
    command: sphinx-build -b html docs build

  examples-base: &examples-base
    <<: *base
    image: hiku-examples
    ports:
      - 5000:5000

  examples-federation:
    <<: *examples-base
    command: python3 examples/graphql_federation.py  
          
  examples-flask:
    <<: *examples-base
    command: python3 examples/graphql_flask.py  
              
  examples-aiohttp:
    <<: *examples-base
    command: python3 examples/graphql_aiohttp.py

  test-base: &test-base
    <<: *base
    image: hiku-tests

  test:
    <<: *test-base
    depends_on:
      - pg
    command: py.test

  pg:
    image: postgres:13-alpine
