version: '3.7'

services:
  base: &base
    image: hiku-base
    working_dir: /work
    user: ${CURRENT_UID}
    volumes:
      - ./hiku:/work/hiku
      - ./tests:/work/tests
      - ./tests_pg:/work/tests_pg
      - ./examples:/work/examples
      - ./docs:/work/docs
      - ./Readme.rst:/work/Readme.rst
      - ./scripts:/work/scripts
      - ./.flake8:/work/.flake8
      - ./pyproject.toml:/work/pyproject.toml
    init: true
    environment:
      PYTHONPATH: .
      PYTHONBUFFERED: 1
      PYTHONWARNINGS: |
        ignore::DeprecationWarning

  dev:
    <<: *base
    image: hiku-dev
    
  docs:
    <<: *base
    image: hiku-docs
    command: pdm run docs

  examples-base: &examples-base
    <<: *base
    image: hiku-examples
    ports:
      - 5000:5000

  examples-federation:
    <<: *examples-base
    command: python3 examples/graphql_federation.py
    
  examples-federation-v2:
    <<: *examples-base
    command: python3 examples/graphql_federation_v2.py
  
  examples-flask:
    <<: *examples-base
    command: python3 examples/graphql_flask.py  
              
  examples-aiohttp:
    <<: *examples-base
    command: python3 examples/graphql_aiohttp.py
    
  federation-compatibility-server:
    <<: *examples-base
    entrypoint: python3 examples/federation-compatibility/server.py
    
  test-base: &test-base
    <<: *base
    image: hiku-tests

  test:
    <<: *test-base
    depends_on:
      - postgres
    command: pdm run test-all

  postgres:
    image: postgres:13-alpine
    init: true
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
