from ..types import TypingMeta as TypingMeta

class TypeDefMeta(TypingMeta):
    def __cls_init__(cls, params) -> None: ...
    def accept(cls, visitor): ...

class TypeDef(metaclass=TypeDefMeta): ...
