from _typeshed import Incomplete
from hiku.graph import Field as Field, Link as Link
from typing import Any, Optional, Union

class DirectiveBase: ...

class Deprecated(DirectiveBase):
    reason: Incomplete
    def __init__(self, reason: Optional[str] = ...) -> None: ...
    def accept(self, visitor: Any) -> Any: ...

def get_deprecated(field: Union['Field', 'Link']) -> Optional[Deprecated]: ...
