from .query import Field as Field, Link as Link, Node as Node
from _typeshed import Incomplete

class Handle:
    __field_name__: Incomplete
    __field_options__: Incomplete
    __field_alias__: Incomplete
    __node_items__: Incomplete
    def __init__(self, name: Incomplete | None = ..., options: Incomplete | None = ..., alias: Incomplete | None = ..., items: Incomplete | None = ...) -> None: ...
    def __getattr__(self, name): ...
    def __getitem__(self, items): ...
    def __lshift__(self, other): ...
    def __call__(self, **options): ...

Q: Incomplete

def build(items): ...
