from ..query import Field as Field, Link as Link, Node as Node, QueryVisitor as QueryVisitor
from graphql.language import ast

class Exporter(QueryVisitor):
    def visit_field(self, obj: Field) -> ast.FieldNode: ...
    def visit_link(self, obj: Link) -> ast.FieldNode: ...
    def visit_node(self, obj: Node) -> ast.SelectionSetNode: ...

def export(query: Node) -> ast.DocumentNode: ...
