from ..protobuf import query_pb2 as query_pb2
from ..query import QueryVisitor as QueryVisitor
from _typeshed import Incomplete

class Exporter(QueryVisitor):
    stack: Incomplete
    def __init__(self, node) -> None: ...
    def visit_field(self, obj) -> None: ...
    def visit_link(self, obj) -> None: ...
    def visit_node(self, obj) -> None: ...

def export(query): ...
