from ..edn import Dict as Dict, Keyword as Keyword, List as List, Set as Set, Tuple as Tuple
from ..query import QueryVisitor as QueryVisitor

class Exporter(QueryVisitor):
    def visit_field(self, obj): ...
    def visit_link(self, obj): ...
    def visit_node(self, obj): ...

def export(query): ...
