# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docs/example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x64ocs/example.proto\"*\n\tCharacter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07species\x18\x02 \x01(\t\"&\n\x04Root\x12\x1e\n\ncharacters\x18\x01 \x03(\x0b\x32\n.Characterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docs.example_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHARACTER']._serialized_start=22
  _globals['_CHARACTER']._serialized_end=64
  _globals['_ROOT']._serialized_start=66
  _globals['_ROOT']._serialized_end=104
# @@protoc_insertion_point(module_scope)
