# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: docs/example.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='docs/example.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x64ocs/example.proto\"*\n\tCharacter\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07species\x18\x02 \x01(\t\"&\n\x04Root\x12\x1e\n\ncharacters\x18\x01 \x03(\x0b\x32\n.Characterb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CHARACTER = _descriptor.Descriptor(
  name='Character',
  full_name='Character',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Character.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='species', full_name='Character.species', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=64,
)


_ROOT = _descriptor.Descriptor(
  name='Root',
  full_name='Root',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='characters', full_name='Root.characters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=104,
)

_ROOT.fields_by_name['characters'].message_type = _CHARACTER
DESCRIPTOR.message_types_by_name['Character'] = _CHARACTER
DESCRIPTOR.message_types_by_name['Root'] = _ROOT

Character = _reflection.GeneratedProtocolMessageType('Character', (_message.Message,), dict(
  DESCRIPTOR = _CHARACTER,
  __module__ = 'docs.example_pb2'
  # @@protoc_insertion_point(class_scope:Character)
  ))
_sym_db.RegisterMessage(Character)

Root = _reflection.GeneratedProtocolMessageType('Root', (_message.Message,), dict(
  DESCRIPTOR = _ROOT,
  __module__ = 'docs.example_pb2'
  # @@protoc_insertion_point(class_scope:Root)
  ))
_sym_db.RegisterMessage(Root)


# @@protoc_insertion_point(module_scope)
