name: Test
on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run pull requests)
  push:
    branches: [master]
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install tox tox-gh-actions codecov
        python -m pip install -r requirements-tox.txt
    - name: Run flake8
      if: startsWith(matrix.python-version, '3.7')
      run: tox -e flake8
    - name: Run mypy
      if: startsWith(matrix.python-version, '3.7')
      run: tox -e mypy
    - name: Run unit tests
      run: tox -- --cov
